import './globals.css'
import { ReactNode, FC } from 'react'
import type { Metadata } from 'next'
import { NavBar } from '@/components'

interface IRootLayout {
    children: ReactNode
}

export const metadata: Metadata = {
    title: 'Web-Chat',
    description: 'Generated by create next app',
}

const RootLayout: FC<IRootLayout> = ({ children }) => {
    return (
        <html lang='en'>
            <body>{children}</body>
        </html>
    )
}

export default RootLayout
