import './globals.css'
import type { Metadata } from 'next'

interface IRootLayout {
    children: React.ReactNode
}

export const metadata: Metadata = {
    title: 'Web-Chat',
    description: 'Generated by create next app',
}

const RootLayout = ({ children }: IRootLayout) => {
    return (
        <html lang='en'>
            <body>{children}</body>
        </html>
    )
}

export default RootLayout
